// Auto-generated by scripts/generate-client.ts using openapi-typescript-codegen style
import type { Http } from "./http";
export class GranolaClient {
	constructor(private http: Http) {}
	public async v1_get_workspaces(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/get-workspaces", body);
	}
	public async v2_get_documents(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v2/get-documents", body);
	}
	public async v1_get_document_metadata(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/get-document-metadata", body);
	}
	public async v1_get_document_transcript(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/get-document-transcript", body);
	}
	public async v1_update_document(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/update-document", body);
	}
	public async v1_update_document_panel(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/update-document-panel", body);
	}
	public async v1_get_panel_templates(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/get-panel-templates", body);
	}
	public async v1_get_people(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/get-people", body);
	}
	public async v1_get_feature_flags(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/get-feature-flags", body);
	}
	public async v1_get_notion_integration(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/get-notion-integration", body);
	}
	public async v1_get_subscriptions(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/get-subscriptions", body);
	}
	public async v1_refresh_google_events(
		body: Record<string, unknown> = {},
	): Promise<unknown> {
		return this.http.post("/v1/refresh-google-events", body);
	}
	public async v1_check_for_update_latest_mac_yml(): Promise<unknown> {
		return this.http.get("/v1/check-for-update/latest-mac.yml");
	}
}
export default GranolaClient;
